name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout StackSlayerBridge
        uses: actions/checkout@v4

      - name: Clone UJobs
        run: git clone https://github.com/SendyNS/UJobs.git

      - name: Build & Install UJobs
        run: |
          cd UJobs
          mvn clean install -DskipTests

      - name: Build StackSlayerBridge
        run: mvn clean package -DskipTests
